version: "3"

# The default docker-compose file for local development

# Usage:
#
#  $ docker-compose build
#  $ docker-compose up
#
#  Navigate to https://localhost
#
# See QUICKSTART.md for preliminaries before running this stack.

# Runs the Flask development server. This stack is sufficient for most
# development needs and so is the default docker-compose option.

services:
  app:
    restart: always
    build: .
    ports:
      - "127.0.0.1:5443:5000"
    links:
      #- mongo:mongo
      - localstack:localstack
      - pg:pg
    volumes:
      - .:/usr/src/apps/StoryMapJS
      - .localstack:/usr/src/apps/StoryMapJS/.localstack
    env_file: .env
    # command: python api.py -s -p 5000
    command: gunicorn --workers 3 -b 0.0.0.0:5000 core.wsgi:application
    depends_on:
      #- mongo
      - pg

  #mongo:
  #  image: mongo:2.4
  #  restart: always
  #  volumes:
  #    - mongodata:/data/db
  #  ports:
  #    - "27017-27019:27017-27019"
  #  environment:
  #    MONGO_INITDB_DATABASE: storymapjs

  pg:
    image: postgres:11.6
    restart: always
    environment:
      POSTGRES_USER: storymap
      POSTGRES_DB: storymap
      POSTGRES_PASSWORD: storymap
    volumes:
      - ./.pgdata:/var/lib/postgresql/data/

  localstack:
    image: localstack/localstack-light
    restart: always
    environment:
      USE_LIGHT_IMAGE: 1
      LOCALSTACK_SERVICES: s3
      DATA_DIR: /tmp/localstack/data
    ports:
      - "127.0.0.1:4566:4566"
    volumes:
      - ./.localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
#volumes:
#  mongodata:
