name: Create and publish a package
on:
  push:
    branches: ['main']
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        repository: ${{ github.repository }}/mapstories
        tag_with_sha: true
        tag_with_ref: true
